version: '3.8'

services:
  # MongoDB for Solana Agent storage
  mongodb:
    image: mongo:latest
    container_name: solana-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=solana
      - MONGO_INITDB_ROOT_PASSWORD=solanapassword
    networks:
      - solana_network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  solana_network:
    name: solana_network
    driver: bridge

volumes:
  mongodb_data:
